//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idea
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<int> PostedByTeacher { get; set; }
        public Nullable<int> PostedByStudent { get; set; }
        public int checker { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
